name        : "Hello Actions"
description : "Greeting DMj Developers"
author      : "djo@dmj.co.mz"

inputs:
    MY_NAME:
        description : "Who to greet?"
        required    : true
        default     : "World"
        
runs:
    using: "docker"
    image: "Dockerfile"
    
branding:
    icon    :"mic"
    color   :"purple"