name: Java CI

on: [push]

jobs:
  gradle:                           #---------------Replaced build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #1
      - name: Set up JDK 1.8        #---------------or 11.0.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.8         #---------------or 11 for ArcGIS
      #2
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      #3
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: /opt/gradle/gradle-5.0/wrapper/
          arguments: build