name: Java C.I with Gradle
on: 
    push:
        branches: [$default-branch]
    #pull_request:
        #branches: [$default-branch]    
jobs:
    build:
        name:   Java C.I. Gradle
        runs-on: ubuntu-latest
        
        #1-Setting java definition
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

         #2-Setting gradle definition
            - name: Grant permission for gradlew
              run : chmod +x gradlew
            - name: Build with Gradle
              run : ./gradlew build

         #3-Executing action-B 
         #   - name: Running actionB
         #  - uses: ./action-b
         #     with:
         #       MY_NAME: "Gradle 5.0"